# Generated by Django 3.2.25 on 2024-08-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cvcvdj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcbcjd", models.BigIntegerField()),
                ("cbxnxk", models.BigIntegerField()),
            ],
        ),
    ]
