# Generated by Django 3.2.25 on 2024-08-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cvcvdj'),
        ('users', '0002_auto_20240819_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_cvcvdj_1_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_cvcvdj_1_1', to='home.cvcvdj'),
        ),
        migrations.AddField(
            model_name='user',
            name='rel_cvcvdj_1_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_cvcvdj_1_n', to='home.cvcvdj'),
        ),
        migrations.AddField(
            model_name='user',
            name='rel_cvcvdj_n_n',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_rel_cvcvdj_n_n', to='home.Cvcvdj'),
        ),
    ]
